quarkus:
  application:
    name: mt-id

  http:
    port: 8081
    cors:
      enabled: true
      origins:
        - ${APP_MT_ID_CORS_ORIGIN:http://localhost:3000}
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      headers:
        - Content-Type
        - Authorization
        - Accept

  mongodb:
    connection-string: ${APP_MT_ID_MONGODB_ENDPOINT:mongodb://localhost:27017/}
    database: ${APP_MT_ID_MONGODB_DATABASE:mt-id}


  swagger-ui:
    title: MT ID API Documentation
    theme: muted
    try-it-out-enabled: true
    persist-authorization: true
    always-include: true
    path: /swagger-ui

  smallrye-openapi:
    info-title: MT ID API Documentation
    info-version: 1.0.0

  rest-client:
    viacep:
      url: ${APP_VIACEP_URL:https://viacep.com.br/ws}
      scope: jakarta.inject.Singleton
      connect-timeout: 10000
      read-timeout: 10000
    kodepos:
      url: ${APP_KODEPOS_URL:https://kodepos.vercel.app}
      scope: jakarta.inject.Singleton
      connect-timeout: 10000
      read-timeout: 10000
    zippopotam:
      url: ${APP_ZIPPOPOTAMUS_URL:http://api.zippopotam.us}
      scope: jakarta.inject.Singleton
      connect-timeout: 10000
      read-timeout: 10000

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: ${APP_MT_ID_JWT_ISSUER:mt-id}

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:di5cbe8ni}
  api-key: ${CLOUDINARY_API_KEY:735658489191162}
  api-secret: ${CLOUDINARY_API_SECRET:GQEvr_ZhAjrhCfrMCP9HUo5WP2M}

app:
  mt:
    id:
      timezone: ${APP_MT_ID_TIMEZONE:America/Sao_Paulo}
      token:
        expiration:
          hours: ${APP_MT_ID_JWT_TOKEN_EXPIRATION_HOURS:24}
      refresh-token:
        expiration:
          days: ${APP_MT_ID_JWT_REFRESH_TOKEN_EXPIRATION_DAYS:30}