package com.mtsolutions.domain.constant;

import lombok.Getter;

@Getter
public enum Country {
    AR("Argentina"),
    AT("Austria"),
    AU("Australia"),
    BE("Belgium"),
    BG("Bulgaria"),
    BH("Bahrain"),
    BO("Bolivia"),
    BR("Brazil"),
    BY("Belarus"),
    CA("Canada"),
    CH("Switzerland"),
    CL("Chile"),
    CN("China"),
    CO("Colombia"),
    CR("Costa Rica"),
    CY("Cyprus"),
    CZ("Czech Republic"),
    DE("Germany"),
    DK("Denmark"),
    DO("Dominican Republic"),
    DZ("Algeria"),
    EC("Ecuador"),
    EE("Estonia"),
    EG("Egypt"),
    ES("Spain"),
    FI("Finland"),
    FR("France"),
    GH("Ghana"),
    GR("Greece"),
    GT("Guatemala"),
    HK("Hong Kong"),
    HR("Croatia"),
    HU("Hungary"),
    ID("Indonesia"),
    IE("Ireland"),
    IL("Israel"),
    IN("India"),
    IS("Iceland"),
    IT("Italy"),
    JO("Jordan"),
    JP("Japan"),
    KE("Kenya"),
    KR("South Korea"),
    KW("Kuwait"),
    KZ("Kazakhstan"),
    LB("Lebanon"),
    LT("Lithuania"),
    LU("Luxembourg"),
    LV("Latvia"),
    MA("Morocco"),
    MX("Mexico"),
    MY("Malaysia"),
    NG("Nigeria"),
    NL("Netherlands"),
    NO("Norway"),
    NZ("New Zealand"),
    OM("Oman"),
    PA("Panama"),
    PE("Peru"),
    PH("Philippines"),
    PK("Pakistan"),
    PL("Poland"),
    PT("Portugal"),
    PY("Paraguay"),
    QA("Qatar"),
    RO("Romania"),
    RS("Serbia"),
    SA("Saudi Arabia"),
    SE("Sweden"),
    SG("Singapore"),
    SI("Slovenia"),
    SK("Slovakia"),
    SV("El Salvador"),
    TH("Thailand"),
    TN("Tunisia"),
    TR("Turkey"),
    TW("Taiwan"),
    UA("Ukraine"),
    UK("United Kingdom"),
    US("United States"),
    UY("Uruguay"),
    VE("Venezuela"),
    VN("Vietnam"),
    ZA("South Africa");

    private final String displayName;

    Country(String displayName) {
        this.displayName = displayName;
    }
}
